name: Daily top 200, 100, 50 global at 6 am

# Controls when the action will run.
on:
    schedule:
        - cron: '00 4 * * *' # Every day at 4am UTC - 6am CET
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-playlist:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.8'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  python -m ipykernel install --user --name python3

            - name: Run top playlists scripts
              working-directory: ./src/target
              env:
                  ID: ${{ secrets.ID }}
                  SECRET: ${{ secrets.SECRET }}
                  URI: ${{ secrets.URI }}
                  REFRESH: ${{ secrets.REFRESH }}
              run: |
                  set PYTHONPATH=%CD%
                  python src/target/run.py

            - name: Commit updated top_200_global.csv
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "Update top_200_global.csv"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
