name: Daily top 200, 100, 50 global at 6 am

# Controls when the action will run.
on:
    schedule:
        - cron: '00 4 * * *' # Every day at 4am UTC - 6am CET
    workflow_dispatch:

permissions:
    contents: write

jobs:
    update-playlist:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12.8'

            - name: Install dependencies and MEGA CLI
              run: |
                  wget https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megacmd-xUbuntu_22.04_amd64.deb && sudo apt install "$PWD/megacmd-xUbuntu_22.04_amd64.deb"
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  python -m ipykernel install --user --name python3

            - name: Top playlists pipelines, Follower reporting
              env:
                  ID: ${{ secrets.ID }}
                  SECRET: ${{ secrets.SECRET }}
                  URI: ${{ secrets.URI }}
                  REFRESH: ${{ secrets.REFRESH }}
                  TELEGRAM_API_KEY: ${{secrets.TELEGRAM_API_KEY}}
                  TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
                  MEGA_LOGIN: ${{secrets.MEGA_LOGIN}}
                  MEGA_PASSWORD: ${{secrets.MEGA_PASSWORD}}
              run: |
                  export PYTHONPATH=$(pwd)
                  python src/target/run.py

            - name: Commit changes
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "Updated top global songs data, created and saved a new follower report"
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
